### PR TITLE
Update colors and logos

### PR DESCRIPTION
**Pull request by oleast**
- Add colors from DS
- Replace old online-logo with the new one
- upgrade packages

### CODE REVIEW

**Comment by aslakhol** [comment]
I dig it, looking fresh.

**Comment by aslakhol** [comment]
I think the constants changes are supposed to belong to your other PR and as such I prefer that we merge that one first, or remove it from this one.

**Comment by oleast** [comment]
> I think the constants changes are supposed to belong to your other PR and as such I prefer that we merge that one first, or remove it from this one.

The changes to constants actually originated here, I just copied them over since I was working on the other branch separately. I don't think it will cause any problems if this is changed first?

**Comment by aslakhol** [comment]
This looks good to merge when conflicts are resolved.

**Pull request merged**
